baseURL = "http://pustserg.github.io/"
languageCode = "en-us"
title = "Sergey Pustovalov"
theme = 'hugo-goa'

[params]
  author="Pustovalov Sergey"
  intro="Ruby backend engineer"
  description="I love ruby app development"
  authorimage="avatar.jpg"
  footercontent="Hire me"

[params.social]
  github="pustserg"
  linkedin="pustserg"
  facebook="pustserg"
  telegram="pustserg"
  email="pustserg@yandex.ru"

[[menu.main]]
