baseURL = "http://pustserg.github.io/"
languageCode = "en-us"
title = "Sergey Pustovalov"
theme = 'hugo-goa'
googleAnalytics = "G-9TSW9K8XTJ"


[params]
  author="Pustovalov Sergey"
  intro="Ruby backend engineer"
  description="I love ruby app development"
  authorimage="avatar.jpg"
  footercontent="Hire me"

[params.social]
  github="pustserg"
  linkedin="pustserg"
  facebook="pustserg"
  telegram="pustserg"
  email="pustserg@yandex.ru"

[params.extra]
  poweredby=true
  rss=false
  copyright="© 2021-2022. Pustovalov Sergey. [Some Rights Reserved](https://creativecommons.org/licenses/by/3.0/)."

[[menu.main]]
